### PR TITLE
Updated persistent binderhub to n852

### PR DESCRIPTION
**Pull request by ctr26**
Hi,

I've updated the repo to work with the latest binderhub and jupyterhub which requires ingress nginx v4, PodDisruptionBudgets are now gone etc.

This deploys for me, but I obviously can't push the new docker image which I had to update to keep the packaging's naming convention.

Thanks

Craig

### CODE REVIEW

**Comment by MridulS** [comment]
Thanks for this @ctr26! I'll review this in the next couple of weeks :)

**Comment by ctr26** [comment]
I did forget to add `cors: "*"` back in after I commented it out, is this critical for anything?

**Comment by arnim** [comment]
@MridulS have you had the chance to review the PR? Can we merge?

**Comment by ctr26** [comment]
@MridulS I'm happy to push the correctly named image to your container repo if you give me permissions.

Thanks

Craig

**Comment by arnim** [comment]
@MridulS  ?

**Comment by arnim** [comment]
Dear @ctr26,

thank you again for this important PR :tada: 

We are in the process of handing over the development for this JHub import functionality (if everything goes well with 2i2c cc @choldgraf :rocket:  ).

Do you have / or plan a deployment of the software at your institution? Have you tested it? & If so... what would be your biggest pros & cons (except our slow response time ;) about the current implementation? Have you been running into any issues while using it? Your feedback would be highly welcome and help us evaluate where we are standing and where we need to go.

Best
Arnim

**Comment by ctr26** [comment]
I'm part of this teamL
https://www.ebi.ac.uk/bioimage-archive/

This is our binder:
binder.bioimagearchive.org

Persistent binder:
login.binder.bioimagearchive.org

Which is deployed here using this repo.
https://github.com/bioimagearchive/bia-binder

Values:
`https://github.com/bioimagearchive/bia-binder/blob/master/binderhub-persistent/config.yaml
`
I'll be maintaining this deployment for a while yet and it's in production it's just obviously very beta at the moment.

We're trying to give people gpu and compute access to biological image data. People like jupyterhub but managing the packages and versions for each hub isn't ideal, hence persistent binderhub.

**Pros** 
- it solves nearly everything regarding packages for users and persistence. 
- it's really well thought-out regarding how it injects and wraps binderhub and jupyterhub together
- People really like having a persistent home drive
**Cons**
- Lack of any obvious way of choosing resources (popping up the jupyterhub profile list would be really nice)
- It was a little fiddly to install with the correct ingress. 

Happy to help with this generally, much prefer it to vanilla jupyterhub deployments.

Thanks

Craig

**Comment by choldgraf** [comment]
@yuvipanda has also been doing some work as part of our collaboration with Pangeo to improve the profile list experience...I bet / hope that one day we will find a way to put binder-style image building in there too :-)

https://twitter.com/yuvipanda/status/1521289262678700032

**Comment by MridulS** [comment]
Sorry for the delayed review @ctr26!

Thanks for the PR, I have built on top of your commits and created a new PR https://github.com/gesiscss/persistent_binderhub/pull/26 which depends on n919. I'll go ahead and close this and merge the other one with your commits.

It would be great if you can upgrade persistent binderhub to check if everything works with the latest release (n919).

Thanks again! 🥳

**Pull request closed without merging**
